from typing import Dict, TypedDict
from BaseClasses import Location

class SS2location(Location):
    game = "System Shock 2"

class LocDict(TypedDict):
    id: int
    region: str
    Option: str
    reqitems: dict #"name": intamount
    reqgroups: set

SS2locations: Dict[str, LocDict] = {
    "body at spawn1": {"id": 45101,
            "region": "medsci1",
            "option": "",
            "reqitems": {},
            "reqgroups": {}},
    "body at spawn2": {"id": 45102,
            "region": "medsci1",
            "option": "",
            "reqitems": {},
            "reqgroups": {}},
    "body at spawn3": {"id": 45103,
            "region": "medsci1",
            "option": "",
            "reqitems": {},
            "reqgroups": {}},
    "body at spawn4": {"id": 45104,
            "region": "medsci1",
            "option": "",
            "reqitems": {},
            "reqgroups": {}},
    "body at spawn5": {"id": 45105,
            "region": "medsci1",
            "option": "",
            "reqitems": {},
            "reqgroups": {}},
    "body at spawn6": {"id": 45106,
            "region": "medsci1",
            "option": "",
            "reqitems": {},
            "reqgroups": {}},
    "body at spawn7": {"id": 45107,
            "region": "medsci1",
            "option": "",
            "reqitems": {},
            "reqgroups": {}},
    "body at spawn8": {"id": 45108,
            "region": "eng1",
            "option": "",
            "reqitems": {},
            "reqgroups": {}},
    "body at spawn9": {"id": 45109,
            "region": "eng1",
            "option": "",
            "reqitems": {},
            "reqgroups": {}},
    "body at spawn10": {"id": 45110,
            "region": "hydro2",
            "option": "",
            "reqitems": {},
            "reqgroups": {}},
    "body at spawn11": {"id": 45111,
            "region": "hydro2",
            "option": "",
            "reqitems": {},
            "reqgroups": {}},
    "body at spawn12": {"id": 45112,
            "region": "hydro2",
            "option": "",
            "reqitems": {},
            "reqgroups": {}},
    "body at spawn13": {"id": 45113,
            "region": "hydro2",
            "option": "",
            "reqitems": {},
            "reqgroups": {}},
    "body at spawn14": {"id": 45114,
            "region": "hydro2",
            "option": "",
            "reqitems": {},
            "reqgroups": {}},
    "body at spawn15": {"id": 45115,
            "region": "hydro2",
            "option": "",
            "reqitems": {},
            "reqgroups": {}},
    "body at spawn16": {"id": 45116,
            "region": "hydro2",
            "option": "",
            "reqitems": {},
            "reqgroups": {}},
    "body at spawn17": {"id": 45117,
            "region": "hydro2",
            "option": "",
            "reqitems": {},
            "reqgroups": {}},
    "body at spawn18": {"id": 45118,
            "region": "hydro3",
            "option": "",
            "reqitems": {},
            "reqgroups": {}},
    "body at spawn19": {"id": 45119,
            "region": "hydro1",
            "option": "",
            "reqitems": {},
            "reqgroups": {}},
    "body at spawn20": {"id": 45120,
            "region": "ops2",
            "option": "",
            "reqitems": {},
            "reqgroups": {}},
    "body at spawn21": {"id": 45121,
            "region": "ops1",
            "option": "",
            "reqitems": {},
            "reqgroups": {}},
    "body at spawn22": {"id": 45122,
            "region": "ops3",
            "option": "",
            "reqitems": {},
            "reqgroups": {}},
    "body at spawn23": {"id": 45123,
            "region": "ops4",
            "option": "",
            "reqitems": {},
            "reqgroups": {}},
    "body at spawn24": {"id": 45124,
            "region": "rec1",
            "option": "",
            "reqitems": {},
            "reqgroups": {}},
    "body at spawn25": {"id": 45125,
            "region": "command1",
            "option": "",
            "reqitems": {},
            "reqgroups": {}},
    "body at spawn26": {"id": 45126,
            "region": "rick1",
            "option": "",
            "reqitems": {},
            "reqgroups": {}},
}